"""Drop Organization Feature Settings

Revision ID: 033016c23fe8
Revises: ef8a7a859321
Create Date: 2025-09-17 17:28:42.815017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '033016c23fe8'
down_revision: Union[str, Sequence[str], None] = 'ef8a7a859321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organizationfeaturesettings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizationfeaturesettings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data_validation', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('match_video', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('robot_pictures', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('scout_schedule', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('picklist', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('organizationfeaturesettings_organization_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('organizationfeaturesettings_pkey')),
    sa.UniqueConstraint('organization_id', name=op.f('organizationfeaturesettings_organization_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
