"""empty message

Revision ID: 109dc5af22cf
Revises: 8f2eac29582d
Create Date: 2025-10-07 15:45:38.652955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '109dc5af22cf'
down_revision: Union[str, Sequence[str], None] = '8f2eac29582d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_event_alliance',
    sa.Column('orgevent_Uid', sa.Uuid(), nullable=False),
    sa.Column('other_organization_id', sa.Integer(), nullable=False),
    sa.Column('org_invite_status', sa.Enum('PENDING', 'ACCEPTED', name='orgeventallianceinvitestatus'), nullable=False),
    sa.ForeignKeyConstraint(['orgevent_Uid'], ['organizationevent.id'], ),
    sa.ForeignKeyConstraint(['other_organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('orgevent_Uid', 'other_organization_id')
    )
    op.drop_table('organization_event_collaboration')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_event_collaboration',
    sa.Column('orgevent_Uid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('other_organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('org_invite_status', postgresql.ENUM('PENDING', 'ACCEPTED', name='orgeventinvitestatus'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['other_organization_id'], ['organization.id'], name=op.f('organization_event_collaboration_other_organization_id_fkey')),
    sa.PrimaryKeyConstraint('orgevent_Uid', 'other_organization_id', name=op.f('organization_event_collaboration_pkey'))
    )
    op.drop_table('organization_event_alliance')
    # ### end Alembic commands ###
