"""Make teamNumber partial primary key

Revision ID: 15a35d4294f5
Revises: fdfb46ad50b9
Create Date: 2025-09-26 11:45:05.439029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15a35d4294f5'
down_revision: Union[str, Sequence[str], None] = 'fdfb46ad50b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matchdata2025', 'notes',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('matchdata2026', 'notes',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matchdata2026', 'notes',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('matchdata2025', 'notes',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
