"""fix outpost naming

Revision ID: 17f4f741b9a6
Revises: 1d9fe712e96b
Create Date: 2026-02-25 16:37:21.903110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17f4f741b9a6'
down_revision: Union[str, Sequence[str], None] = '1d9fe712e96b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitdata2026', sa.Column('autoPickupOutpost', sa.Boolean(), nullable=False))
    op.drop_column('pitdata2026', 'autoPickupDepot')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitdata2026', sa.Column('autoPickupDepot', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('pitdata2026', 'autoPickupOutpost')
    # ### end Alembic commands ###
