"""Create 2026 Schema

Revision ID: 1c32300b49d6
Revises: 839e2cbb3f20
Create Date: 2026-01-20 11:39:39.151951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision: str = '1c32300b49d6'
down_revision: Union[str, Sequence[str], None] = '839e2cbb3f20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matchpredictions2026',
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('event_key', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
    sa.Column('match_number', sa.Integer(), nullable=False),
    sa.Column('match_level', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('red_alliance_win_pct', sa.Float(), nullable=False),
    sa.Column('blue_alliance_win_pct', sa.Float(), nullable=False),
    sa.Column('n_samples', sa.Integer(), nullable=False),
    sa.Column('red_energized_rp', sa.Float(), nullable=False),
    sa.Column('blue_energized_rp', sa.Float(), nullable=False),
    sa.Column('red_supercharged_rp', sa.Float(), nullable=False),
    sa.Column('blue_supercharged_rp', sa.Float(), nullable=False),
    sa.Column('red_traversal_rp', sa.Float(), nullable=False),
    sa.Column('blue_traversal_rp', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['event_key'], ['frcevent.event_key'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['season'], ['season.id'], ),
    sa.PrimaryKeyConstraint('event_key', 'match_number', 'match_level', 'organization_id')
    )
    op.create_table('picklistgenerator2026',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('favorited', sa.Boolean(), nullable=False),
    sa.Column('autonomous_fuel', sa.Float(), nullable=False),
    sa.Column('autonomous_pass', sa.Float(), nullable=False),
    sa.Column('autonomous_climb', sa.Float(), nullable=False),
    sa.Column('autonomous_points', sa.Float(), nullable=False),
    sa.Column('teleop_fuel', sa.Float(), nullable=False),
    sa.Column('teleop_pass', sa.Float(), nullable=False),
    sa.Column('endgame_points', sa.Float(), nullable=False),
    sa.Column('total_fuel', sa.Float(), nullable=False),
    sa.Column('total_climb', sa.Float(), nullable=False),
    sa.Column('total_points', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['season'], ['season.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pitdata2026',
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('team_number', sa.Integer(), nullable=False),
    sa.Column('event_key', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('robot_weight', sa.Integer(), nullable=True),
    sa.Column('drivetrain', ENUM(name='drivetrain', create_type=False), nullable=False),
    sa.Column('driveteam', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hopperCapacity', sa.Integer(), nullable=False),
    sa.Column('pickupGround', sa.Boolean(), nullable=False),
    sa.Column('pickupFeeder', sa.Boolean(), nullable=False),
    sa.Column('trenchBot', sa.Boolean(), nullable=False),
    sa.Column('bumpBot', sa.Boolean(), nullable=False),
    sa.Column('startPositionTrenchLeft', sa.Boolean(), nullable=False),
    sa.Column('startPositionBumpLeft', sa.Boolean(), nullable=False),
    sa.Column('startPositionCenter', sa.Boolean(), nullable=False),
    sa.Column('startPositionBumpRight', sa.Boolean(), nullable=False),
    sa.Column('startPositionTrenchRight', sa.Boolean(), nullable=False),
    sa.Column('autoPickupCorral', sa.Boolean(), nullable=False),
    sa.Column('autoPickupDepot', sa.Boolean(), nullable=False),
    sa.Column('autoFuel', sa.Boolean(), nullable=False),
    sa.Column('autoFuelCount', sa.Integer(), nullable=False),
    sa.Column('autoPass', sa.Boolean(), nullable=False),
    sa.Column('autoPassCount', sa.Integer(), nullable=False),
    sa.Column('autoClimb', sa.Boolean(), nullable=False),
    sa.Column('autoNotes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('teleFuel', sa.Boolean(), nullable=False),
    sa.Column('telePass', sa.Boolean(), nullable=False),
    sa.Column('teleNotes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('endgame', sa.Enum('NONE', 'L1', 'L2', 'L3', name='pitendgame2026'), nullable=False),
    sa.Column('overallNotes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['event_key'], ['frcevent.event_key'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['season'], ['season.id'], ),
    sa.ForeignKeyConstraint(['team_number'], ['teamrecord.team_number'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('team_number', 'event_key', 'user_id')
    )
    op.create_table('prescout2026',
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('team_number', sa.Integer(), nullable=False),
    sa.Column('event_key', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
    sa.Column('match_number', sa.Integer(), nullable=False),
    sa.Column('match_level', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('autoFuel', sa.Integer(), nullable=False),
    sa.Column('autoPass', sa.Integer(), nullable=False),
    sa.Column('autoClimb', sa.Integer(), nullable=False),
    sa.Column('teleopFuel', sa.Integer(), nullable=False),
    sa.Column('teleopPass', sa.Integer(), nullable=False),
    sa.Column('endgame', sa.Enum('NONE', 'L1', 'L2', 'L3', name='endgame2026'), nullable=False),
    sa.ForeignKeyConstraint(['event_key'], ['frcevent.event_key'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['season'], ['season.id'], ),
    sa.ForeignKeyConstraint(['team_number'], ['teamrecord.team_number'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('team_number', 'event_key', 'match_number', 'match_level', 'user_id')
    )
    op.create_table('tbamatchdata2026',
    sa.Column('event_key', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
    sa.Column('match_number', sa.Integer(), nullable=False),
    sa.Column('match_level', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('alliance', ENUM(name="alliance", create_type=False), nullable=False),
    sa.Column('rp', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('autoFuel', sa.Integer(), nullable=False),
    sa.Column('bot1AutoClimb', sa.Boolean(), nullable=False),
    sa.Column('bot2AutoClimb', sa.Boolean(), nullable=False),
    sa.Column('bot3AutoClimb', sa.Boolean(), nullable=False),
    sa.Column('teleopFuel', sa.Integer(), nullable=False),
    sa.Column('bot1endgame', sa.Enum('NONE', 'L1', 'L2', 'L3', name='endgame2026'), nullable=False),
    sa.Column('bot2endgame', sa.Enum('NONE', 'L1', 'L2', 'L3', name='endgame2026'), nullable=False),
    sa.Column('bot3endgame', sa.Enum('NONE', 'L1', 'L2', 'L3', name='endgame2026'), nullable=False),
    sa.Column('wonAuto', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_key'], ['frcevent.event_key'], ),
    sa.PrimaryKeyConstraint('event_key', 'match_number', 'match_level', 'alliance')
    )
    op.drop_constraint(op.f('datavalidation_unique'), 'datavalidation', type_='unique')
    op.add_column('matchdata2026', sa.Column('autoFuel', sa.Integer(), nullable=False))
    op.add_column('matchdata2026', sa.Column('autoPass', sa.Integer(), nullable=False))
    op.add_column('matchdata2026', sa.Column('autoClimb', sa.Integer(), nullable=False))
    op.add_column('matchdata2026', sa.Column('teleopFuel', sa.Integer(), nullable=False))
    op.add_column('matchdata2026', sa.Column('teleopPass', sa.Integer(), nullable=False))
    op.add_column('matchdata2026', sa.Column('endgame', sa.Enum('NONE', 'L1', 'L2', 'L3', name='endgame2026'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matchdata2026', 'endgame')
    op.drop_column('matchdata2026', 'teleopPass')
    op.drop_column('matchdata2026', 'teleopFuel')
    op.drop_column('matchdata2026', 'autoClimb')
    op.drop_column('matchdata2026', 'autoPass')
    op.drop_column('matchdata2026', 'autoFuel')
    op.create_unique_constraint(op.f('datavalidation_unique'), 'datavalidation', ['event_key', 'match_number', 'match_level', 'user_id', 'team_number', 'organization_id'], postgresql_nulls_not_distinct=False)
    op.drop_table('tbamatchdata2026')
    op.drop_table('prescout2026')
    op.drop_table('pitdata2026')
    op.drop_table('picklistgenerator2026')
    op.drop_table('matchpredictions2026')
    # ### end Alembic commands ###
