"""Add no show to starting position options

Revision ID: 1d9fe712e96b
Revises: e317a30cebcd
Create Date: 2026-02-25 10:35:04.322375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d9fe712e96b'
down_revision: Union[str, Sequence[str], None] = 'e317a30cebcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE startingposition2026 ADD VALUE 'NOSHOW';")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
