"""Remove Foreign Keys

Revision ID: 25554b9b4391
Revises: fefe59ac8264
Create Date: 2025-09-16 23:49:46.139054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25554b9b4391'
down_revision: Union[str, Sequence[str], None] = 'fefe59ac8264'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('userorganization_event_key_fkey'), 'userorganization', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('userorganization_event_key_fkey'), 'userorganization', 'frcevent', ['event_key'], ['event_key'])
    # ### end Alembic commands ###
