"""empty message

Revision ID: 43d041b5c205
Revises: b5dba61366fa
Create Date: 2025-10-07 11:49:53.159531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '43d041b5c205'
down_revision: Union[str, Sequence[str], None] = 'b5dba61366fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matchpredictions2025',
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('event_key', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
    sa.Column('match_number', sa.Integer(), nullable=False),
    sa.Column('match_level', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('red_alliance_win_pct', sa.Float(), nullable=False),
    sa.Column('blue_alliance_win_pct', sa.Float(), nullable=False),
    sa.Column('n_samples', sa.Integer(), nullable=False),
    sa.Column('red_auto_rp', sa.Float(), nullable=False),
    sa.Column('blue_auto_rp', sa.Float(), nullable=False),
    sa.Column('red_endgame_rp', sa.Float(), nullable=False),
    sa.Column('blue_endgame_rp', sa.Float(), nullable=False),
    sa.Column('red_w_coral_rp', sa.Float(), nullable=False),
    sa.Column('blue_w_coral_rp', sa.Float(), nullable=False),
    sa.Column('red_r_coral_rp', sa.Float(), nullable=False),
    sa.Column('blue_r_coral_rp', sa.Float(), nullable=False),
    sa.Column('red_rw_win_pct', sa.Float(), nullable=False),
    sa.Column('blue_rw_win_pct', sa.Float(), nullable=False),
    sa.Column('red_wr_win_pct', sa.Float(), nullable=False),
    sa.Column('blue_wr_win_pct', sa.Float(), nullable=False),
    sa.Column('red_rr_win_pct', sa.Float(), nullable=False),
    sa.Column('blue_rr_win_pct', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['event_key'], ['frcevent.event_key'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['season'], ['season.id'], ),
    sa.PrimaryKeyConstraint('event_key', 'match_number', 'match_level', 'organization_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matchpredictions2025')
    # ### end Alembic commands ###
