"""Add score to tba match data base

Revision ID: 47be4764472f
Revises: 8e61e28f74ab
Create Date: 2025-10-27 21:33:57.883278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47be4764472f'
down_revision: Union[str, Sequence[str], None] = '8e61e28f74ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbamatchdata2025', sa.Column('score', sa.Integer(), nullable=True))
    op.add_column('tbamatchdata2025', sa.Column('coop', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbamatchdata2025', 'coop')
    op.drop_column('tbamatchdata2025', 'score')
    # ### end Alembic commands ###
