"""Add logged in userOrg to user table

Revision ID: 4a957e8f68d6
Revises: e0596e092419
Create Date: 2025-09-24 22:11:55.310146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a957e8f68d6'
down_revision: Union[str, Sequence[str], None] = 'e0596e092419'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('logged_in_user_org', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'logged_in_user_org')
    # ### end Alembic commands ###
