"""Attempt to fix Foreign Keys

Revision ID: 4b543e8eb4c7
Revises: 25554b9b4391
Create Date: 2025-09-17 00:03:46.657604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b543e8eb4c7'
down_revision: Union[str, Sequence[str], None] = '25554b9b4391'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
