"""Add picklisting

Revision ID: 4f7c4a40ec5a
Revises: de03ebd3f765
Create Date: 2025-10-01 12:58:31.738395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4f7c4a40ec5a'
down_revision: Union[str, Sequence[str], None] = 'de03ebd3f765'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('picklist',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('event_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('favorited', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_key'], ['frcevent.event_key'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['season'], ['season.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('picklistgenerator2025',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('favorited', sa.Boolean(), nullable=False),
    sa.Column('al4c', sa.Float(), nullable=False),
    sa.Column('al3c', sa.Float(), nullable=False),
    sa.Column('al2c', sa.Float(), nullable=False),
    sa.Column('al1c', sa.Float(), nullable=False),
    sa.Column('autonomous_coral', sa.Float(), nullable=False),
    sa.Column('autonomous_algae', sa.Float(), nullable=False),
    sa.Column('autonomous_points', sa.Float(), nullable=False),
    sa.Column('tl4c', sa.Float(), nullable=False),
    sa.Column('tl3c', sa.Float(), nullable=False),
    sa.Column('tl2c', sa.Float(), nullable=False),
    sa.Column('tl1c', sa.Float(), nullable=False),
    sa.Column('teleop_coral', sa.Float(), nullable=False),
    sa.Column('teleop_algae', sa.Float(), nullable=False),
    sa.Column('teleop_points', sa.Float(), nullable=False),
    sa.Column('aNet', sa.Float(), nullable=False),
    sa.Column('tNet', sa.Float(), nullable=False),
    sa.Column('aProcessor', sa.Float(), nullable=False),
    sa.Column('tProcessor', sa.Float(), nullable=False),
    sa.Column('endgame_points', sa.Float(), nullable=False),
    sa.Column('total_coral', sa.Float(), nullable=False),
    sa.Column('total_algae', sa.Float(), nullable=False),
    sa.Column('total_game_pieces', sa.Float(), nullable=False),
    sa.Column('total_points', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['season'], ['season.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('picklist_rank',
    sa.Column('picklist_id', sa.Uuid(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('team_number', sa.Integer(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dnp', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['picklist_id'], ['picklist.id'], ),
    sa.ForeignKeyConstraint(['team_number'], ['teamrecord.team_number'], ),
    sa.PrimaryKeyConstraint('picklist_id', 'rank')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('picklist_rank')
    op.drop_table('picklistgenerator2025')
    op.drop_table('picklist')
    # ### end Alembic commands ###
