"""TBA Match data refactor

Revision ID: 65da27296aeb
Revises: f3a86eeb4596
Create Date: 2025-09-26 14:57:26.103542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65da27296aeb'
down_revision: Union[str, Sequence[str], None] = 'f3a86eeb4596'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbamatchdata2025', sa.Column('net', sa.Integer(), nullable=False))
    op.add_column('tbamatchdata2025', sa.Column('processor', sa.Integer(), nullable=False))
    op.drop_column('tbamatchdata2025', 'aProcessor')
    op.drop_column('tbamatchdata2025', 'tNet')
    op.drop_column('tbamatchdata2025', 'aNet')
    op.drop_column('tbamatchdata2025', 'tProcessor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbamatchdata2025', sa.Column('tProcessor', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tbamatchdata2025', sa.Column('aNet', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tbamatchdata2025', sa.Column('tNet', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tbamatchdata2025', sa.Column('aProcessor', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('tbamatchdata2025', 'processor')
    op.drop_column('tbamatchdata2025', 'net')
    # ### end Alembic commands ###
