"""Add active to seasons

Revision ID: 839e2cbb3f20
Revises: 35b28c53cc01
Create Date: 2025-10-28 12:35:33.817058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '839e2cbb3f20'
down_revision: Union[str, Sequence[str], None] = '35b28c53cc01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('season', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('season', 'active')
    # ### end Alembic commands ###
