"""Add pitscouting

Revision ID: 87efcf39ea99
Revises: 4f7c4a40ec5a
Create Date: 2025-10-03 16:30:40.048263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '87efcf39ea99'
down_revision: Union[str, Sequence[str], None] = '4f7c4a40ec5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pitdata2025',
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('team_number', sa.Integer(), nullable=False),
    sa.Column('event_key', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('robot_weight', sa.Integer(), nullable=True),
    sa.Column('drivetrain', sa.Enum('SWERVE', 'TANK', 'MECANUM', 'HDRIVE', 'OTHER', name='drivetrain'), nullable=False),
    sa.Column('driveteam', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('startPositionLeft', sa.Boolean(), nullable=False),
    sa.Column('startPositionCenter', sa.Boolean(), nullable=False),
    sa.Column('startPositionRight', sa.Boolean(), nullable=False),
    sa.Column('pickupGround', sa.Boolean(), nullable=False),
    sa.Column('pickupFeeder', sa.Boolean(), nullable=False),
    sa.Column('autoL4Coral', sa.Boolean(), nullable=False),
    sa.Column('autoL3Coral', sa.Boolean(), nullable=False),
    sa.Column('autoL2Coral', sa.Boolean(), nullable=False),
    sa.Column('autoL1Coral', sa.Boolean(), nullable=False),
    sa.Column('autoCoralCount', sa.Integer(), nullable=False),
    sa.Column('autoAlgaeNet', sa.Integer(), nullable=False),
    sa.Column('autoAlgaeProcessor', sa.Integer(), nullable=False),
    sa.Column('autoNotes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('teleL4Coral', sa.Boolean(), nullable=False),
    sa.Column('teleL3Coral', sa.Boolean(), nullable=False),
    sa.Column('teleL2Coral', sa.Boolean(), nullable=False),
    sa.Column('teleL1Coral', sa.Boolean(), nullable=False),
    sa.Column('teleAlgaeNet', sa.Boolean(), nullable=False),
    sa.Column('teleAlgaeProcessor', sa.Boolean(), nullable=False),
    sa.Column('teleNotes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('endgame', sa.Enum('NONE', 'PARK', 'SHALLOW', 'DEEP', name='pitendgame2025'), nullable=False),
    sa.Column('overallNotes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['event_key'], ['frcevent.event_key'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['season'], ['season.id'], ),
    sa.ForeignKeyConstraint(['team_number'], ['teamrecord.team_number'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('team_number', 'event_key', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pitdata2025')
    # ### end Alembic commands ###
