"""Add RP to tba match data base

Revision ID: 8e61e28f74ab
Revises: f76ef3554d14
Create Date: 2025-10-27 21:24:23.431194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e61e28f74ab'
down_revision: Union[str, Sequence[str], None] = 'f76ef3554d14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbamatchdata2025', sa.Column('rp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbamatchdata2025', 'rp')
    # ### end Alembic commands ###
