"""empty message

Revision ID: 8f2eac29582d
Revises: 148caa396f2b
Create Date: 2025-10-07 15:34:56.918713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f2eac29582d'
down_revision: Union[str, Sequence[str], None] = '148caa396f2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_event_collaboration',
    sa.Column('orgevent_Uid', sa.Uuid(), nullable=False),
    sa.Column('other_organization_id', sa.Integer(), nullable=False),
    sa.Column('org_invite_status', sa.Enum('PENDING', 'ACCEPTED', name='orgeventinvitestatus'), nullable=False),
    sa.ForeignKeyConstraint(['other_organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('orgevent_Uid', 'other_organization_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization_event_collaboration')
    # ### end Alembic commands ###
