"""Attempt to fix Foreign Keys 4

Revision ID: 96b71f1cf2e8
Revises: ab2c76a916dc
Create Date: 2025-09-17 00:17:04.783339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96b71f1cf2e8'
down_revision: Union[str, Sequence[str], None] = 'ab2c76a916dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
