"""Convert to MatchData parent

Revision ID: 9d4ca4da2950
Revises: bca65c338b4e
Create Date: 2025-09-17 18:07:19.417068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9d4ca4da2950'
down_revision: Union[str, Sequence[str], None] = 'bca65c338b4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('season',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('matchdata2025', sa.Column('season', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'matchdata2025', 'season', ['season'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'matchdata2025', type_='foreignkey')
    op.drop_column('matchdata2025', 'season')
    op.drop_table('season')
    # ### end Alembic commands ###
