"""Attempt to fix Foreign Keys 5

Revision ID: aa1590806cbc
Revises: 96b71f1cf2e8
Create Date: 2025-09-17 00:19:44.155709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa1590806cbc'
down_revision: Union[str, Sequence[str], None] = '96b71f1cf2e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
