"""empty message

Revision ID: b5dba61366fa
Revises: dc7d8789dfc7
Create Date: 2025-10-07 11:18:16.556532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b5dba61366fa'
down_revision: Union[str, Sequence[str], None] = 'dc7d8789dfc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statbotics_data',
    sa.Column('event_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('team_number', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Float(), nullable=False),
    sa.Column('auto_points', sa.Float(), nullable=False),
    sa.Column('teleop_points', sa.Float(), nullable=False),
    sa.Column('endgame_points', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['event_key'], ['frcevent.event_key'], ),
    sa.ForeignKeyConstraint(['team_number'], ['teamrecord.team_number'], ),
    sa.PrimaryKeyConstraint('event_key', 'team_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statbotics_data')
    # ### end Alembic commands ###
