"""Re-add Organization Feature Settings

Revision ID: bca65c338b4e
Revises: 033016c23fe8
Create Date: 2025-09-17 17:29:17.895945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bca65c338b4e'
down_revision: Union[str, Sequence[str], None] = '033016c23fe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizationfeaturesettings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('data_validation', sa.Boolean(), nullable=False),
    sa.Column('match_video', sa.Boolean(), nullable=False),
    sa.Column('robot_pictures', sa.Boolean(), nullable=False),
    sa.Column('scout_schedule', sa.Boolean(), nullable=False),
    sa.Column('picklist', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organizationfeaturesettings')
    # ### end Alembic commands ###
