"""TBA Match data refactor

Revision ID: dbda8cb603ad
Revises: 65da27296aeb
Create Date: 2025-09-26 16:00:25.503180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dbda8cb603ad'
down_revision: Union[str, Sequence[str], None] = '65da27296aeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbamatchdata2025', sa.Column('bot1endgame', sa.Enum('NONE', 'PARK', 'SHALLOW', 'DEEP', name='endgame2025'), nullable=False))
    op.add_column('tbamatchdata2025', sa.Column('bot2endgame', sa.Enum('NONE', 'PARK', 'SHALLOW', 'DEEP', name='endgame2025'), nullable=False))
    op.add_column('tbamatchdata2025', sa.Column('bot3endgame', sa.Enum('NONE', 'PARK', 'SHALLOW', 'DEEP', name='endgame2025'), nullable=False))
    op.drop_column('tbamatchdata2025', 'endgame')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbamatchdata2025', sa.Column('endgame', postgresql.ENUM('NONE', 'PARK', 'SHALLOW', 'DEEP', name='endgame2025'), autoincrement=False, nullable=False))
    op.drop_column('tbamatchdata2025', 'bot3endgame')
    op.drop_column('tbamatchdata2025', 'bot2endgame')
    op.drop_column('tbamatchdata2025', 'bot1endgame')
    # ### end Alembic commands ###
