"""empty message

Revision ID: dc7d8789dfc7
Revises: 1e1e4c9feab0
Create Date: 2025-10-06 17:42:41.304385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'dc7d8789dfc7'
down_revision: Union[str, Sequence[str], None] = '1e1e4c9feab0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('superscout_2025',
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('team_number', sa.Integer(), nullable=False),
    sa.Column('event_key', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
    sa.Column('match_number', sa.Integer(), nullable=False),
    sa.Column('match_level', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stopped_moving', sa.Boolean(), nullable=False),
    sa.Column('dead_lt_45_seconds', sa.Boolean(), nullable=False),
    sa.Column('dead_gt_45_seconds', sa.Boolean(), nullable=False),
    sa.Column('slow_drive', sa.Boolean(), nullable=False),
    sa.Column('fast_drive', sa.Boolean(), nullable=False),
    sa.Column('good_driving', sa.Boolean(), nullable=False),
    sa.Column('bad_driving', sa.Boolean(), nullable=False),
    sa.Column('drops_game_pieces', sa.Boolean(), nullable=False),
    sa.Column('lots_of_fouls', sa.Boolean(), nullable=False),
    sa.Column('tipped', sa.Boolean(), nullable=False),
    sa.Column('didnt_move', sa.Boolean(), nullable=False),
    sa.Column('broken', sa.Boolean(), nullable=False),
    sa.Column('no_show', sa.Boolean(), nullable=False),
    sa.Column('dnp', sa.Boolean(), nullable=False),
    sa.Column('played_defense', sa.Boolean(), nullable=False),
    sa.Column('received_defense', sa.Boolean(), nullable=False),
    sa.Column('yellow_card', sa.Boolean(), nullable=False),
    sa.Column('red_card', sa.Boolean(), nullable=False),
    sa.Column('defense_rating', sa.Integer(), nullable=True),
    sa.Column('driver_rating', sa.Integer(), nullable=True),
    sa.Column('robot_overall', sa.Integer(), nullable=False),
    sa.Column('startPosition', sa.Enum('LEFT', 'CENTER', 'RIGHT', name='startingposition2025'), nullable=True),
    sa.Column('floor_algae', sa.Boolean(), nullable=False),
    sa.Column('floor_coral', sa.Boolean(), nullable=False),
    sa.Column('holds_both_pieces', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_key'], ['frcevent.event_key'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['season'], ['season.id'], ),
    sa.ForeignKeyConstraint(['team_number'], ['teamrecord.team_number'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('team_number', 'event_key', 'match_number', 'match_level', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('superscout_2025')
    # ### end Alembic commands ###
