"""Add picklist generation

Revision ID: de03ebd3f765
Revises: dbda8cb603ad
Create Date: 2025-09-30 18:10:29.707787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'de03ebd3f765'
down_revision: Union[str, Sequence[str], None] = 'dbda8cb603ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventrankings',
    sa.Column('event_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('team_number', sa.Integer(), nullable=False),
    sa.Column('ranking_points', sa.Integer(), nullable=False),
    sa.Column('matches_played', sa.Integer(), nullable=False),
    sa.Column('ranking_tiebreaker_1', sa.Float(), nullable=False),
    sa.Column('ranking_tiebreaker_2', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['event_key'], ['frcevent.event_key'], ),
    sa.ForeignKeyConstraint(['team_number'], ['teamrecord.team_number'], ),
    sa.PrimaryKeyConstraint('event_key', 'rank')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eventrankings')
    # ### end Alembic commands ###
