"""Add week to FRCEvent

Revision ID: ef8a7a859321
Revises: 615c5f999268
Create Date: 2025-09-17 12:46:37.906048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef8a7a859321'
down_revision: Union[str, Sequence[str], None] = '615c5f999268'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('frcevent', sa.Column('week', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('frcevent', 'week')
    # ### end Alembic commands ###
