"""Make alliance partial primary key on TBA data

Revision ID: f18c0cd11d2e
Revises: 15a35d4294f5
Create Date: 2025-09-26 11:51:55.920217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f18c0cd11d2e'
down_revision: Union[str, Sequence[str], None] = '15a35d4294f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
