"""TBA Match data refactor

Revision ID: f3a86eeb4596
Revises: f18c0cd11d2e
Create Date: 2025-09-26 14:31:18.023950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3a86eeb4596'
down_revision: Union[str, Sequence[str], None] = 'f18c0cd11d2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tbamatchdata2025_team_number_fkey'), 'tbamatchdata2025', type_='foreignkey')
    op.drop_column('tbamatchdata2025', 'team_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbamatchdata2025', sa.Column('team_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('tbamatchdata2025_team_number_fkey'), 'tbamatchdata2025', 'teamrecord', ['team_number'], ['team_number'])
    # ### end Alembic commands ###
