"""Add autoassign user org and site admin tables

Revision ID: f76ef3554d14
Revises: 33a93dd2cd5d
Create Date: 2025-10-20 23:44:49.957338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f76ef3554d14'
down_revision: Union[str, Sequence[str], None] = '33a93dd2cd5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_assign_user_org',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_admins',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_admins')
    op.drop_table('auto_assign_user_org')
    # ### end Alembic commands ###
