"""Add teamNumber to dataValidation table

Revision ID: fdfb46ad50b9
Revises: 4a957e8f68d6
Create Date: 2025-09-26 11:24:58.678836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdfb46ad50b9'
down_revision: Union[str, Sequence[str], None] = '4a957e8f68d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datavalidation', sa.Column('team_number', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'datavalidation', 'teamrecord', ['team_number'], ['team_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'datavalidation', type_='foreignkey')
    op.drop_column('datavalidation', 'team_number')
    # ### end Alembic commands ###
